# YML For CircleCI Job
version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t mikeyvxt/noxim:$TAG .
      - run:
          name: Default config test
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker run mikeyvxt/noxim:$TAG -config /opt/noxim/config_examples/default_config.yaml -power /opt/noxim/bin/power.yaml
      - run:
          name: Push latest tag to DockerHub
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mikeyvxt/noxim:$TAG
