# YML For CircleCI Job
version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container
          command: |
            docker build -t mikeyvxt/noxim .
      - run:
          name: Default config test
          command: |
            docker run mikeyvxt/noxim -config /opt/noxim/config_examples/default_config.yaml -power /opt/noxim/bin/power.yaml
